---

language: 'python'
python: '2.7'

sudo: required

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y grub-pc

install: True

script:
  - 'git clone --depth 1 https://github.com/nickjj/rolespec'
  - 'cd rolespec ; bin/rolespec -r https://github.com/scibi/test-suite'
