---

language: 'python'
python: '2.7'

sudo: required

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y grub-pc
  - sudo bash -c echo -e '#!/bin/bash\necho /dev/sda1' ">" /usr/sbin/grub-probe

install: True

script:
  - 'git clone --depth 1 https://github.com/nickjj/rolespec'
  - 'cd rolespec ; bin/rolespec -r https://github.com/scibi/test-suite'
