---

language: 'python'
python: '2.7'

sudo: required

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y grub-pc
  - echo -e '#!/bin/bash\necho /dev/sda1' > /tmp/grub-probe.tmp
  - ls -l /tmp/grub-probe.tmp
  - chmod a+x /tmp/grub-probe.tmp
  - ls -l /usr/sbin/grub-probe
  - sudo bash -c 'mv /usr/sbin/grub-probe /usr/sbin/grub-probe.orig; mv /tmp/grub-probe.tmp /usr/sbin/grub-probe'
  - ls -l /usr/sbin/grub-probe
  - ls -l /boot/grub/
  - sudo mkdir /boot/grub/i386-pc/
  - ls -l /boot/grub/i386-pc/
  - sudo touch /boot/grub/i386-pc/serial.mod

install: True

script:
  - 'git clone --depth 1 https://github.com/nickjj/rolespec'
  - 'cd rolespec ; bin/rolespec -r https://github.com/scibi/test-suite'
