---
# tasks file for debops.serial_console


- name: Set kernel console parameters
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=' 
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ grub_kernel_options }}{% if grub_serial_console_enable %} console=tty0 console=ttyS{{ grub_serial_console_unit }},{{ grub_serial_console_speed }}n8{% endif %}"'
    state: present
  notify: Update grub

- name: Set grub terminal
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_TERMINAL='
    line: 'GRUB_TERMINAL="serial console"'
    state: present
  notify: Update grub
  when: grub_serial_console_enable

- name: Set grub serial parameters
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_SERIAL_COMMAND='
    line: 'GRUB_SERIAL_COMMAND="serial --unit={{ grub_serial_console_unit }} --speed={{ grub_serial_console_speed }} --word=8 --parity=no --stop=1"'
    state: present
  notify: Update grub
  when: grub_serial_console_enable

