---
# tasks file for debops.serial_console

- name: Divert original /etc/default/grub
  command: dpkg-divert --quiet --local --divert /etc/default/grub.dpkg-divert --rename /etc/default/grub
  args:
    creates: '/etc/default/grub.dpkg-divert'

- name: Get default kernel parameters
  shell: . /etc/default/grub.dpkg-divert; echo $GRUB_CMDLINE_LINUX_DEFAULT | sed -e 's,\bquiet\b,,'
  register: grub_register_default_cmdline
  changed_when: False
  when: grub_save_options

- name: Default kernel parameters
  set_fact:
    grub_fact_default_kernel_parameters: '{{ grub_register_default_cmdline.stdout }}'
  when: grub_save_options

- name: Configure /etc/default/grub
  template:
    src: 'etc/default/grub.j2'
    dest: '/etc/default/grub'
    owner:  'root'
    group:  'root'
    mode:   '0644'
  notify: Update grub


